"""add folio paid amount

Revision ID: 4a896dd83aa2
Revises: 951efc97c195
Create Date: 2026-09-16 06:58:15.786124

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a896dd83aa2"
down_revision: str | Sequence[str] | None = "951efc97c195"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "folios",
        sa.Column("paid_amount", sa.Numeric(precision=12, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("folios", "paid_amount")
    # ### end Alembic commands ###
