"""create folio tables

Revision ID: 951efc97c195
Revises: cca671cf8ff5
Create Date: 2026-09-15 21:41:27.121253

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "951efc97c195"
down_revision: str | Sequence[str] | None = "cca671cf8ff5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("folio_number", sa.String(length=30), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_folios_booking_id"), "folios", ["booking_id"], unique=True)
    op.create_index(
        op.f("ix_folios_folio_number"), "folios", ["folio_number"], unique=True
    )
    op.create_table(
        "folio_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("folio_id", sa.Integer(), nullable=False),
        sa.Column("item_type", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["folio_id"],
            ["folios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_folio_items_folio_id"), "folio_items", ["folio_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_folio_items_folio_id"), table_name="folio_items")
    op.drop_table("folio_items")
    op.drop_index(op.f("ix_folios_folio_number"), table_name="folios")
    op.drop_index(op.f("ix_folios_booking_id"), table_name="folios")
    op.drop_table("folios")
    # ### end Alembic commands ###
