"""create payments table

Revision ID: ac64458bc832
Revises: 951efc97c195
Create Date: 2026-09-16 08:36:56.309390

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac64458bc832"
down_revision: str | Sequence[str] | None = "951efc97c195"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("payment_reference", sa.String(length=30), nullable=False),
        sa.Column("folio_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("payment_method", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("received_by", sa.Integer(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["folio_id"],
            ["folios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["received_by"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payments_external_reference"),
        "payments",
        ["external_reference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payments_folio_id"), "payments", ["folio_id"], unique=False
    )
    op.create_index(
        op.f("ix_payments_payment_reference"),
        "payments",
        ["payment_reference"],
        unique=True,
    )
    op.drop_column("folios", "paid_amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "folios",
        sa.Column(
            "paid_amount",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_payments_payment_reference"), table_name="payments")
    op.drop_index(op.f("ix_payments_folio_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_external_reference"), table_name="payments")
    op.drop_table("payments")
    # ### end Alembic commands ###
