"""create rooms table

Revision ID: b6321ab502ea
Revises: 5f6d94f8ceb8
Create Date: 2026-09-13 18:54:08.653818

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6321ab502ea"
down_revision: str | Sequence[str] | None = "5f6d94f8ceb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("room_number", sa.String(length=20), nullable=False),
        sa.Column("room_name", sa.String(length=100), nullable=False),
        sa.Column("room_type", sa.String(length=50), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rooms_room_number"), "rooms", ["room_number"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rooms_room_number"), table_name="rooms")
    op.drop_table("rooms")
    # ### end Alembic commands ###
